GET http://localhost:8000/auth/repositories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g