GET http://localhost:8000/auth/repositories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmRoaW1hbmFuMTgxMEBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW5HYW5kaGlBbHQiLCJpZCI6ImNtYmNscTk3bzAwMDB0em1heDRpZXJmZjAiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTc0OTA1OTE2M30.9RYQlcem6Z8jL9w46RachxMF9OLYh2Jotg-wT0eebto