### Create a new project
# @name createProject
POST http://localhost:8000/project/create?repo=https://github.com/MananGandhiAlt/MananGandhiAlt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmRoaW1hbmFuMTgxMEBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW5HYW5kaGlBbHQiLCJpZCI6ImNtYmNscTk3bzAwMDB0em1heDRpZXJmZjAiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTc0ODcxODMwN30.aGWo4w6flo3UDhrsKrhxe3b01nSUYT152AnmoZhra8g

### Get project list
# @name getProjects
GET http://localhost:8000/project/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmRoaW1hbmFuMTgxMEBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW5HYW5kaGlBbHQiLCJpZCI6ImNtYmNscTk3bzAwMDB0em1heDRpZXJmZjAiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTc0ODcxODMwN30.aGWo4w6flo3UDhrsKrhxe3b01nSUYT152AnmoZhra8g

### Get specific project data
# @name getProject
GET http://localhost:8000/project/cmbdi8v0y0001tz2bd2jcx1kz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmRoaW1hbmFuMTgxMEBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW5HYW5kaGlBbHQiLCJpZCI6ImNtYmNscTk3bzAwMDB0em1heDRpZXJmZjAiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTc0ODcxODMwN30.aGWo4w6flo3UDhrsKrhxe3b01nSUYT152AnmoZhra8g

### Provision project container (first time)
# @name provisionProject
POST http://localhost:8000/project/cmbdi8v0y0001tz2bd2jcx1kz/provision
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhbmRoaW1hbmFuMTgxMEBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW5HYW5kaGlBbHQiLCJpZCI6ImNtYmNscTk3bzAwMDB0em1heDRpZXJmZjAiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTc0ODcxODMwN30.aGWo4w6flo3UDhrsKrhxe3b01nSUYT152AnmoZhra8g

### Access code-server homepage (GET request) - No auth required
# @name accessCodeServerHome
GET http://localhost:8000/project/cmbdi8v0y0001tz2bd2jcx1kz/provision/use/