### Create a new project
# @name createProject
POST http://localhost:8000/project/create?repo=https://github.com/MananGandhiAlt/MananGandhiAlt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get project list
# @name getProjects
GET http://localhost:8000/project/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get specific project data
# @name getProject
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Provision project container (first time)
# @name provisionProject
POST http://localhost:8000/project/cmbntdz460002tzadkp820um8/provision
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Access code-server homepage (GET request) - No auth required
# @name accessCodeServerHome
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/provision/use/

### Send a chat message to a project
# @name projectChat
POST http://localhost:8000/project/cmbntdz460002tzadkp820um8/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

{
  "owner": "MananGandhiAlt",
  "repo": "test-123",
  "messages": [
    {
      "role": "user",
      "content": "Hello, what can you tell me about this project?"
    }
  ]
}

### Get project readme
# @name getProjectReadme
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/readme
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get project diagram
# @name getProjectDiagram
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/diagram
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get project bugs
# @name getProjectBugs
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/bugs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get project mocks
# @name getProjectMocks
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/mocks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g

### Get project tests
# @name getProjectTests
GET http://localhost:8000/project/cmbntdz460002tzadkp820um8/tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZHVtYW5hbkBnbWFpbC5jb20iLCJuYW1lIjoiTWFuYW4gR2FuZGhpIiwiaWQiOiJjbWJudGRoNm8wMDAwdHphZHU5eXdrb2NjIiwic2NvcGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDkzOTYyNzV9.zfJn6OWHKs9h-MztlnIAXmzgZZ1-jXqGn72Bghauw1g