import Link from "next/link";
import { Github, Home, FolderGit2 } from "lucide-react";
import { Outfit } from "next/font/google";
import { Button } from "@/components/ui/button";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "YetiCodes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen ${outfit.className}`}>
        <div className="fixed inset-0 -z-10">
          <img
            src="https://id-preview--cc5f56e0-6f7c-42ea-a708-591b65dccafa.lovable.app/Header-background.webp"
            alt="Background"
            className="h-full w-full object-cover invert"
          />
          <div className="absolute inset-0 bg-background/90" />
        </div>
        <nav className="fixed top-0 left-0 right-0 z-50 bg-background/60 border-b border-border/40 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-16 items-center mx-auto px-5">
            <Link href="/" className="flex items-center space-x-2">
              <Github className="h-6 w-6" />
              <span className="font-bold">DevAI</span>
            </Link>
            <div className="flex items-center space-x-4 ml-auto">
              <Link href="/">
                <Button variant="ghost" size="sm">
                  <Home className="h-4 w-4 mr-2" />
                  Home
                </Button>
              </Link>

              <Link href="/dashboard">
                <Button variant="ghost" size="sm">
                  <FolderGit2 className="h-4 w-4 mr-2" />
                  Your Projects
                </Button>
              </Link>
            </div>
          </div>
        </nav>
        <main className="container pt-16 mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
